/**
 * Feeling definitions for tag autocomplete and tooltips
 * Based on Marshall Rosenberg's Nonviolent Communication emotions
 * Source: db/seed-feelings.sql
 */

export interface FeelingDefinition {
    feeling: string
    category: 'positive' | 'negative'
    definition: string
}

export const FEELING_DEFINITIONS: Record<string, FeelingDefinition> = {
    // Positive feelings (when needs are being met)
    'absorbed': { feeling: 'absorbed', category: 'positive', definition: 'Completely engaged and focused' },
    'adventurous': { feeling: 'adventurous', category: 'positive', definition: 'Eager to explore new experiences' },
    'affectionate': { feeling: 'affectionate', category: 'positive', definition: 'Showing fondness and care' },
    'alert': { feeling: 'alert', category: 'positive', definition: 'Mentally sharp and aware' },
    'alive': { feeling: 'alive', category: 'positive', definition: 'Full of energy and vitality' },
    'amazed': { feeling: 'amazed', category: 'positive', definition: 'Filled with wonder and surprise' },
    'amused': { feeling: 'amused', category: 'positive', definition: 'Finding something entertaining or funny' },
    'animated': { feeling: 'animated', category: 'positive', definition: 'Lively and enthusiastic' },
    'appreciative': { feeling: 'appreciative', category: 'positive', definition: 'Grateful and thankful' },
    'ardent': { feeling: 'ardent', category: 'positive', definition: 'Passionate and intense' },
    'aroused': { feeling: 'aroused', category: 'positive', definition: 'Stimulated and excited' },
    'astonished': { feeling: 'astonished', category: 'positive', definition: 'Greatly surprised' },
    'blissful': { feeling: 'blissful', category: 'positive', definition: 'Perfectly happy and content' },
    'breathless': { feeling: 'breathless', category: 'positive', definition: 'Excited to the point of breathlessness' },
    'buoyant': { feeling: 'buoyant', category: 'positive', definition: 'Cheerful and optimistic' },
    'calm': { feeling: 'calm', category: 'positive', definition: 'Peaceful and tranquil' },
    'carefree': { feeling: 'carefree', category: 'positive', definition: 'Free from worry or responsibility' },
    'cheerful': { feeling: 'cheerful', category: 'positive', definition: 'Happy and optimistic' },
    'comfortable': { feeling: 'comfortable', category: 'positive', definition: 'At ease and relaxed' },
    'complacent': { feeling: 'complacent', category: 'positive', definition: 'Satisfied with oneself' },
    'composed': { feeling: 'composed', category: 'positive', definition: 'Calm and in control' },
    'concerned': { feeling: 'concerned', category: 'positive', definition: 'Caring and attentive' },
    'confident': { feeling: 'confident', category: 'positive', definition: 'Self-assured and certain' },
    'content': { feeling: 'content', category: 'positive', definition: 'Satisfied and happy' },
    'cool': { feeling: 'cool', category: 'positive', definition: 'Calm and composed' },
    'curious': { feeling: 'curious', category: 'positive', definition: 'Eager to learn or know' },
    'dazzled': { feeling: 'dazzled', category: 'positive', definition: 'Impressed and amazed' },
    'delighted': { feeling: 'delighted', category: 'positive', definition: 'Very pleased and happy' },
    'eager': { feeling: 'eager', category: 'positive', definition: 'Keen and enthusiastic' },
    'ebullient': { feeling: 'ebullient', category: 'positive', definition: 'Cheerful and full of energy' },
    'ecstatic': { feeling: 'ecstatic', category: 'positive', definition: 'Extremely happy' },
    'effervescent': { feeling: 'effervescent', category: 'positive', definition: 'Vivacious and enthusiastic' },
    'elated': { feeling: 'elated', category: 'positive', definition: 'Very happy and excited' },
    'enchanted': { feeling: 'enchanted', category: 'positive', definition: 'Delighted and charmed' },
    'encouraged': { feeling: 'encouraged', category: 'positive', definition: 'Given confidence and support' },
    'energetic': { feeling: 'energetic', category: 'positive', definition: 'Full of energy' },
    'engrossed': { feeling: 'engrossed', category: 'positive', definition: 'Completely absorbed' },
    'enlivened': { feeling: 'enlivened', category: 'positive', definition: 'Made more lively' },
    'enthusiastic': { feeling: 'enthusiastic', category: 'positive', definition: 'Eager and passionate' },
    'excited': { feeling: 'excited', category: 'positive', definition: 'Very enthusiastic and eager' },
    'exhilarated': { feeling: 'exhilarated', category: 'positive', definition: 'Very happy and elated' },
    'expansive': { feeling: 'expansive', category: 'positive', definition: 'Open and generous' },
    'expectant': { feeling: 'expectant', category: 'positive', definition: 'Eagerly awaiting' },
    'exultant': { feeling: 'exultant', category: 'positive', definition: 'Triumphantly happy' },
    'fascinated': { feeling: 'fascinated', category: 'positive', definition: 'Extremely interested' },
    'free': { feeling: 'free', category: 'positive', definition: 'Not constrained or restricted' },
    'friendly': { feeling: 'friendly', category: 'positive', definition: 'Kind and pleasant' },
    'fulfilled': { feeling: 'fulfilled', category: 'positive', definition: 'Satisfied and complete' },
    'glad': { feeling: 'glad', category: 'positive', definition: 'Pleased and happy' },
    'gleeful': { feeling: 'gleeful', category: 'positive', definition: 'Delightedly happy' },
    'glorious': { feeling: 'glorious', category: 'positive', definition: 'Magnificent and wonderful' },
    'glowing': { feeling: 'glowing', category: 'positive', definition: 'Radiating happiness' },
    'good-humored': { feeling: 'good-humored', category: 'positive', definition: 'Cheerful and pleasant' },
    'grateful': { feeling: 'grateful', category: 'positive', definition: 'Thankful and appreciative' },
    'gratified': { feeling: 'gratified', category: 'positive', definition: 'Pleased and satisfied' },
    'happy': { feeling: 'happy', category: 'positive', definition: 'Feeling joy and contentment' },
    'helpful': { feeling: 'helpful', category: 'positive', definition: 'Willing to assist others' },
    'hopeful': { feeling: 'hopeful', category: 'positive', definition: 'Optimistic about the future' },
    'inquisitive': { feeling: 'inquisitive', category: 'positive', definition: 'Curious and questioning' },
    'inspired': { feeling: 'inspired', category: 'positive', definition: 'Filled with creative energy' },
    'intense': { feeling: 'intense', category: 'positive', definition: 'Deeply felt and strong' },
    'interested': { feeling: 'interested', category: 'positive', definition: 'Curious and engaged' },
    'intrigued': { feeling: 'intrigued', category: 'positive', definition: 'Fascinated and curious' },
    'invigorated': { feeling: 'invigorated', category: 'positive', definition: 'Energized and refreshed' },
    'involved': { feeling: 'involved', category: 'positive', definition: 'Engaged and participating' },
    'joyous': { feeling: 'joyous', category: 'positive', definition: 'Full of joy' },
    'joyful': { feeling: 'joyful', category: 'positive', definition: 'Feeling great happiness' },
    'jubilant': { feeling: 'jubilant', category: 'positive', definition: 'Triumphantly joyful' },
    'keyed-up': { feeling: 'keyed-up', category: 'positive', definition: 'Excited and energetic' },
    'loving': { feeling: 'loving', category: 'positive', definition: 'Feeling or showing love' },
    'mellow': { feeling: 'mellow', category: 'positive', definition: 'Relaxed and easygoing' },
    'merry': { feeling: 'merry', category: 'positive', definition: 'Cheerful and lively' },
    'mirthful': { feeling: 'mirthful', category: 'positive', definition: 'Full of laughter and joy' },
    'moved': { feeling: 'moved', category: 'positive', definition: 'Emotionally affected' },
    'optimistic': { feeling: 'optimistic', category: 'positive', definition: 'Hopeful about the future' },
    'overjoyed': { feeling: 'overjoyed', category: 'positive', definition: 'Extremely happy' },
    'overwhelmed': { feeling: 'overwhelmed', category: 'positive', definition: 'Overcome with positive emotion' },
    'peaceful': { feeling: 'peaceful', category: 'positive', definition: 'Calm and tranquil' },
    'perky': { feeling: 'perky', category: 'positive', definition: 'Lively and cheerful' },
    'pleasant': { feeling: 'pleasant', category: 'positive', definition: 'Agreeable and enjoyable' },
    'pleased': { feeling: 'pleased', category: 'positive', definition: 'Happy and satisfied' },
    'proud': { feeling: 'proud', category: 'positive', definition: 'Feeling satisfaction in achievements' },
    'quiet': { feeling: 'quiet', category: 'positive', definition: 'Peaceful and calm' },
    'radiant': { feeling: 'radiant', category: 'positive', definition: 'Glowing with happiness' },
    'rapturous': { feeling: 'rapturous', category: 'positive', definition: 'Filled with great joy' },
    'refreshed': { feeling: 'refreshed', category: 'positive', definition: 'Restored and revitalized' },
    'relaxed': { feeling: 'relaxed', category: 'positive', definition: 'Free from tension' },
    'relieved': { feeling: 'relieved', category: 'positive', definition: 'Free from anxiety or distress' },
    'satisfied': { feeling: 'satisfied', category: 'positive', definition: 'Content and fulfilled' },
    'secure': { feeling: 'secure', category: 'positive', definition: 'Safe and protected' },
    'sensitive': { feeling: 'sensitive', category: 'positive', definition: 'Aware and responsive' },
    'serene': { feeling: 'serene', category: 'positive', definition: 'Calm and peaceful' },
    'spellbound': { feeling: 'spellbound', category: 'positive', definition: 'Captivated and fascinated' },
    'splendid': { feeling: 'splendid', category: 'positive', definition: 'Excellent and impressive' },
    'stimulated': { feeling: 'stimulated', category: 'positive', definition: 'Excited and energized' },
    'surprised': { feeling: 'surprised', category: 'positive', definition: 'Unexpectedly pleased' },
    'tender': { feeling: 'tender', category: 'positive', definition: 'Gentle and caring' },
    'thankful': { feeling: 'thankful', category: 'positive', definition: 'Grateful and appreciative' },
    'thrilled': { feeling: 'thrilled', category: 'positive', definition: 'Extremely excited' },
    'touched': { feeling: 'touched', category: 'positive', definition: 'Emotionally moved' },
    'tranquil': { feeling: 'tranquil', category: 'positive', definition: 'Calm and peaceful' },
    'trusting': { feeling: 'trusting', category: 'positive', definition: 'Having confidence in others' },
    'upbeat': { feeling: 'upbeat', category: 'positive', definition: 'Optimistic and cheerful' },
    'warm': { feeling: 'warm', category: 'positive', definition: 'Friendly and affectionate' },
    'wide-awake': { feeling: 'wide-awake', category: 'positive', definition: 'Alert and energetic' },
    'wonderful': { feeling: 'wonderful', category: 'positive', definition: 'Excellent and delightful' },
    'zestful': { feeling: 'zestful', category: 'positive', definition: 'Full of energy and enthusiasm' },

    // Negative feelings (when needs are not being met)
    'afraid': { feeling: 'afraid', category: 'negative', definition: 'Feeling fear or anxiety' },
    'aggravated': { feeling: 'aggravated', category: 'negative', definition: 'Annoyed and frustrated' },
    'agitated': { feeling: 'agitated', category: 'negative', definition: 'Troubled and restless' },
    'alarmed': { feeling: 'alarmed', category: 'negative', definition: 'Worried and frightened' },
    'aloof': { feeling: 'aloof', category: 'negative', definition: 'Distant and uninvolved' },
    'angry': { feeling: 'angry', category: 'negative', definition: 'Feeling strong displeasure' },
    'anguished': { feeling: 'anguished', category: 'negative', definition: 'Experiencing severe mental distress' },
    'annoyed': { feeling: 'annoyed', category: 'negative', definition: 'Slightly angry and irritated' },
    'anxious': { feeling: 'anxious', category: 'negative', definition: 'Worried and uneasy' },
    'apathetic': { feeling: 'apathetic', category: 'negative', definition: 'Lacking interest or enthusiasm' },
    'apprehensive': { feeling: 'apprehensive', category: 'negative', definition: 'Anxious about the future' },
    'ashamed': { feeling: 'ashamed', category: 'negative', definition: 'Feeling guilt or embarrassment' },
    'beat': { feeling: 'beat', category: 'negative', definition: 'Exhausted and worn out' },
    'bewildered': { feeling: 'bewildered', category: 'negative', definition: 'Confused and perplexed' },
    'bitter': { feeling: 'bitter', category: 'negative', definition: 'Angry and resentful' },
    'blah': { feeling: 'blah', category: 'negative', definition: 'Feeling uninspired or apathetic' },
    'blue': { feeling: 'blue', category: 'negative', definition: 'Sad and melancholy' },
    'bored': { feeling: 'bored', category: 'negative', definition: 'Uninterested and restless' },
    'brokenhearted': { feeling: 'brokenhearted', category: 'negative', definition: 'Deeply saddened' },
    'chagrined': { feeling: 'chagrined', category: 'negative', definition: 'Distressed and embarrassed' },
    'cold': { feeling: 'cold', category: 'negative', definition: 'Unfriendly and distant' },
    'confused': { feeling: 'confused', category: 'negative', definition: 'Unable to understand clearly' },
    'cross': { feeling: 'cross', category: 'negative', definition: 'Annoyed and bad-tempered' },
    'dejected': { feeling: 'dejected', category: 'negative', definition: 'Sad and dispirited' },
    'depressed': { feeling: 'depressed', category: 'negative', definition: 'Feeling very unhappy' },
    'despairing': { feeling: 'despairing', category: 'negative', definition: 'Without hope' },
    'despondent': { feeling: 'despondent', category: 'negative', definition: 'In low spirits from loss of hope' },
    'detached': { feeling: 'detached', category: 'negative', definition: 'Emotionally distant' },
    'disaffected': { feeling: 'disaffected', category: 'negative', definition: 'Dissatisfied and rebellious' },
    'disappointed': { feeling: 'disappointed', category: 'negative', definition: 'Sad from unmet expectations' },
    'discouraged': { feeling: 'discouraged', category: 'negative', definition: 'Having lost confidence' },
    'disenchanted': { feeling: 'disenchanted', category: 'negative', definition: 'Disillusioned' },
    'disgruntled': { feeling: 'disgruntled', category: 'negative', definition: 'Angry and dissatisfied' },
    'disgusted': { feeling: 'disgusted', category: 'negative', definition: 'Feeling revulsion' },
    'disheartened': { feeling: 'disheartened', category: 'negative', definition: 'Having lost hope' },
    'dismayed': { feeling: 'dismayed', category: 'negative', definition: 'Distressed and troubled' },
    'displeased': { feeling: 'displeased', category: 'negative', definition: 'Annoyed and dissatisfied' },
    'disquieted': { feeling: 'disquieted', category: 'negative', definition: 'Worried and uneasy' },
    'distressed': { feeling: 'distressed', category: 'negative', definition: 'Suffering from anxiety' },
    'disturbed': { feeling: 'disturbed', category: 'negative', definition: 'Worried and upset' },
    'downcast': { feeling: 'downcast', category: 'negative', definition: 'Feeling dejected' },
    'downhearted': { feeling: 'downhearted', category: 'negative', definition: 'Discouraged and sad' },
    'dull': { feeling: 'dull', category: 'negative', definition: 'Lacking interest or excitement' },
    'edgy': { feeling: 'edgy', category: 'negative', definition: 'Tense and irritable' },
    'embarrassed': { feeling: 'embarrassed', category: 'negative', definition: 'Feeling awkward and self-conscious' },
    'embittered': { feeling: 'embittered', category: 'negative', definition: 'Angry and resentful' },
    'exasperated': { feeling: 'exasperated', category: 'negative', definition: 'Extremely annoyed' },
    'exhausted': { feeling: 'exhausted', category: 'negative', definition: 'Extremely tired' },
    'fatigued': { feeling: 'fatigued', category: 'negative', definition: 'Very tired' },
    'fearful': { feeling: 'fearful', category: 'negative', definition: 'Afraid and anxious' },
    'fidgety': { feeling: 'fidgety', category: 'negative', definition: 'Restless and impatient' },
    'forlorn': { feeling: 'forlorn', category: 'negative', definition: 'Lonely and abandoned' },
    'frightened': { feeling: 'frightened', category: 'negative', definition: 'Afraid and scared' },
    'frustrated': { feeling: 'frustrated', category: 'negative', definition: 'Feeling blocked or thwarted' },
    'furious': { feeling: 'furious', category: 'negative', definition: 'Extremely angry' },
    'gloomy': { feeling: 'gloomy', category: 'negative', definition: 'Sad and pessimistic' },
    'guilty': { feeling: 'guilty', category: 'negative', definition: 'Feeling responsible for wrongdoing' },
    'harried': { feeling: 'harried', category: 'negative', definition: 'Feeling pressured and stressed' },
    'heavy': { feeling: 'heavy', category: 'negative', definition: 'Weighed down emotionally' },
    'helpless': { feeling: 'helpless', category: 'negative', definition: 'Unable to help oneself' },
    'hesitant': { feeling: 'hesitant', category: 'negative', definition: 'Tentative and uncertain' },
    'horrible': { feeling: 'horrible', category: 'negative', definition: 'Extremely unpleasant' },
    'horrified': { feeling: 'horrified', category: 'negative', definition: 'Filled with horror' },
    'hostile': { feeling: 'hostile', category: 'negative', definition: 'Unfriendly and aggressive' },
    'hot': { feeling: 'hot', category: 'negative', definition: 'Angry and heated' },
    'humdrum': { feeling: 'humdrum', category: 'negative', definition: 'Lacking excitement, dull' },
    'hurt': { feeling: 'hurt', category: 'negative', definition: 'Emotionally wounded' },
    'impatient': { feeling: 'impatient', category: 'negative', definition: 'Restless and eager' },
    'indifferent': { feeling: 'indifferent', category: 'negative', definition: 'Having no interest' },
    'irate': { feeling: 'irate', category: 'negative', definition: 'Very angry' },
    'irked': { feeling: 'irked', category: 'negative', definition: 'Irritated and annoyed' },
    'irritated': { feeling: 'irritated', category: 'negative', definition: 'Annoyed and impatient' },
    'jealous': { feeling: 'jealous', category: 'negative', definition: 'Envious and possessive' },
    'jittery': { feeling: 'jittery', category: 'negative', definition: 'Nervous and restless' },
    'lazy': { feeling: 'lazy', category: 'negative', definition: 'Unwilling to work or be active' },
    'leery': { feeling: 'leery', category: 'negative', definition: 'Wary and suspicious' },
    'lethargic': { feeling: 'lethargic', category: 'negative', definition: 'Sluggish and lacking energy' },
    'listless': { feeling: 'listless', category: 'negative', definition: 'Lacking energy and enthusiasm' },
    'lonely': { feeling: 'lonely', category: 'negative', definition: 'Sad from being alone' },
    'mad': { feeling: 'mad', category: 'negative', definition: 'Angry and furious' },
    'mean': { feeling: 'mean', category: 'negative', definition: 'Unkind and spiteful' },
    'miserable': { feeling: 'miserable', category: 'negative', definition: 'Very unhappy' },
    'mopey': { feeling: 'mopey', category: 'negative', definition: 'Dejected and listless' },
    'morose': { feeling: 'morose', category: 'negative', definition: 'Sullen and ill-tempered' },
    'mournful': { feeling: 'mournful', category: 'negative', definition: 'Feeling grief or sorrow' },
    'nervous': { feeling: 'nervous', category: 'negative', definition: 'Anxious and worried' },
    'nettled': { feeling: 'nettled', category: 'negative', definition: 'Irritated and annoyed' },
    'numb': { feeling: 'numb', category: 'negative', definition: 'Unable to feel emotions' },
    'panicky': { feeling: 'panicky', category: 'negative', definition: 'Feeling sudden overwhelming fear' },
    'passive': { feeling: 'passive', category: 'negative', definition: 'Accepting without resistance' },
    'perplexed': { feeling: 'perplexed', category: 'negative', definition: 'Confused and puzzled' },
    'pessimistic': { feeling: 'pessimistic', category: 'negative', definition: 'Expecting the worst' },
    'puzzled': { feeling: 'puzzled', category: 'negative', definition: 'Confused and uncertain' },
    'rancorous': { feeling: 'rancorous', category: 'negative', definition: 'Bitter and resentful' },
    'reluctant': { feeling: 'reluctant', category: 'negative', definition: 'Unwilling and hesitant' },
    'repelled': { feeling: 'repelled', category: 'negative', definition: 'Disgusted and repulsed' },
    'resentful': { feeling: 'resentful', category: 'negative', definition: 'Bitter and indignant' },
    'restless': { feeling: 'restless', category: 'negative', definition: 'Unable to rest or relax' },
    'sad': { feeling: 'sad', category: 'negative', definition: 'Feeling sorrow' },
    'scared': { feeling: 'scared', category: 'negative', definition: 'Frightened and afraid' },
    'shaky': { feeling: 'shaky', category: 'negative', definition: 'Unsteady and nervous' },
    'shocked': { feeling: 'shocked', category: 'negative', definition: 'Surprised and disturbed' },
    'skeptical': { feeling: 'skeptical', category: 'negative', definition: 'Doubtful and questioning' },
    'sleepy': { feeling: 'sleepy', category: 'negative', definition: 'Drowsy and tired' },
    'sorrowful': { feeling: 'sorrowful', category: 'negative', definition: 'Full of grief' },
    'sorry': { feeling: 'sorry', category: 'negative', definition: 'Feeling regret' },
    'spiritless': { feeling: 'spiritless', category: 'negative', definition: 'Lacking energy or enthusiasm' },
    'startled': { feeling: 'startled', category: 'negative', definition: 'Suddenly surprised' },
    'suspicious': { feeling: 'suspicious', category: 'negative', definition: 'Distrustful and wary' },
    'tepid': { feeling: 'tepid', category: 'negative', definition: 'Showing little enthusiasm' },
    'terrified': { feeling: 'terrified', category: 'negative', definition: 'Extremely frightened' },
    'tired': { feeling: 'tired', category: 'negative', definition: 'Needing rest' },
    'troubled': { feeling: 'troubled', category: 'negative', definition: 'Worried and distressed' },
    'uncomfortable': { feeling: 'uncomfortable', category: 'negative', definition: 'Feeling unease' },
    'unconcerned': { feeling: 'unconcerned', category: 'negative', definition: 'Not worried or interested' },
    'uneasy': { feeling: 'uneasy', category: 'negative', definition: 'Anxious and restless' },
    'unglued': { feeling: 'unglued', category: 'negative', definition: 'Emotionally falling apart' },
    'unhappy': { feeling: 'unhappy', category: 'negative', definition: 'Not happy or content' },
    'unnerved': { feeling: 'unnerved', category: 'negative', definition: 'Disturbed and unsettled' },
    'unsteady': { feeling: 'unsteady', category: 'negative', definition: 'Not stable or secure' },
    'upset': { feeling: 'upset', category: 'negative', definition: 'Troubled and distressed' },
    'uptight': { feeling: 'uptight', category: 'negative', definition: 'Tense and anxious' },
    'vexed': { feeling: 'vexed', category: 'negative', definition: 'Annoyed and frustrated' },
    'weary': { feeling: 'weary', category: 'negative', definition: 'Tired and exhausted' },
    'wistful': { feeling: 'wistful', category: 'negative', definition: 'Yearning and melancholy' },
    'withdrawn': { feeling: 'withdrawn', category: 'negative', definition: 'Socially detached' },
    'woeful': { feeling: 'woeful', category: 'negative', definition: 'Full of woe and sorrow' },
    'worried': { feeling: 'worried', category: 'negative', definition: 'Anxious about something' },
    'wretched': { feeling: 'wretched', category: 'negative', definition: 'Very unhappy and unfortunate' }
}

/**
 * Get feeling definition by name
 */
export function getFeelingDefinition(feeling: string): string | undefined {
    return FEELING_DEFINITIONS[feeling.toLowerCase()]?.definition
}

/**
 * Get all feelings by category
 */
export function getFeelingsByCategory(category: 'positive' | 'negative'): FeelingDefinition[] {
    return Object.values(FEELING_DEFINITIONS).filter(def => def.category === category)
}

/**
 * Search feelings by partial name
 */
export function searchFeelings(query: string): FeelingDefinition[] {
    const searchTerm = query.toLowerCase()
    return Object.values(FEELING_DEFINITIONS)
        .filter(def => def.feeling.toLowerCase().includes(searchTerm))
        .sort((a, b) => a.feeling.localeCompare(b.feeling))
}
