-- Seed feeling words for autocomplete functionality
-- Based on emotions from Marshall Rosenberg's Nonviolent Communication
-- Usage: These can be used to populate feeling tags with autocomplete suggestions

-- Create feeling_definitions table for hover tooltips
CREATE TABLE IF NOT EXISTS feeling_definitions (
    id SERIAL PRIMARY KEY,
    feeling TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL, -- 'positive' or 'negative'
    definition TEXT
);

-- Insert positive feelings (when needs are being met)
INSERT INTO feeling_definitions (feeling, category, definition) VALUES
('absorbed', 'positive', 'Completely engaged and focused'),
('adventurous', 'positive', 'Eager to explore new experiences'),
('affectionate', 'positive', 'Showing fondness and care'),
('alert', 'positive', 'Mentally sharp and aware'),
('alive', 'positive', 'Full of energy and vitality'),
('amazed', 'positive', 'Filled with wonder and surprise'),
('amused', 'positive', 'Finding something entertaining or funny'),
('animated', 'positive', 'Lively and enthusiastic'),
('appreciative', 'positive', 'Grateful and thankful'),
('ardent', 'positive', 'Passionate and intense'),
('aroused', 'positive', 'Stimulated and excited'),
('astonished', 'positive', 'Greatly surprised'),
('blissful', 'positive', 'Perfectly happy and content'),
('breathless', 'positive', 'Excited to the point of breathlessness'),
('buoyant', 'positive', 'Cheerful and optimistic'),
('calm', 'positive', 'Peaceful and tranquil'),
('carefree', 'positive', 'Free from worry or responsibility'),
('cheerful', 'positive', 'Happy and optimistic'),
('comfortable', 'positive', 'At ease and relaxed'),
('complacent', 'positive', 'Satisfied with oneself'),
('composed', 'positive', 'Calm and in control'),
('concerned', 'positive', 'Caring and attentive'),
('confident', 'positive', 'Self-assured and certain'),
('content', 'positive', 'Satisfied and happy'),
('cool', 'positive', 'Calm and composed'),
('curious', 'positive', 'Eager to learn or know'),
('dazzled', 'positive', 'Impressed and amazed'),
('delighted', 'positive', 'Very pleased and happy'),
('eager', 'positive', 'Keen and enthusiastic'),
('ebullient', 'positive', 'Cheerful and full of energy'),
('ecstatic', 'positive', 'Extremely happy'),
('effervescent', 'positive', 'Vivacious and enthusiastic'),
('elated', 'positive', 'Very happy and excited'),
('enchanted', 'positive', 'Delighted and charmed'),
('encouraged', 'positive', 'Given confidence and support'),
('energetic', 'positive', 'Full of energy'),
('engrossed', 'positive', 'Completely absorbed'),
('enlivened', 'positive', 'Made more lively'),
('enthusiastic', 'positive', 'Eager and passionate'),
('excited', 'positive', 'Very enthusiastic and eager'),
('exhilarated', 'positive', 'Very happy and elated'),
('expansive', 'positive', 'Open and generous'),
('expectant', 'positive', 'Eagerly awaiting'),
('exultant', 'positive', 'Triumphantly happy'),
('fascinated', 'positive', 'Extremely interested'),
('free', 'positive', 'Not constrained or restricted'),
('friendly', 'positive', 'Kind and pleasant'),
('fulfilled', 'positive', 'Satisfied and complete'),
('glad', 'positive', 'Pleased and happy'),
('gleeful', 'positive', 'Delightedly happy'),
('glorious', 'positive', 'Magnificent and wonderful'),
('glowing', 'positive', 'Radiating happiness'),
('good-humored', 'positive', 'Cheerful and pleasant'),
('grateful', 'positive', 'Thankful and appreciative'),
('gratified', 'positive', 'Pleased and satisfied'),
('happy', 'positive', 'Feeling joy and contentment'),
('helpful', 'positive', 'Willing to assist others'),
('hopeful', 'positive', 'Optimistic about the future'),
('inquisitive', 'positive', 'Curious and questioning'),
('inspired', 'positive', 'Filled with creative energy'),
('intense', 'positive', 'Deeply felt and strong'),
('interested', 'positive', 'Curious and engaged'),
('intrigued', 'positive', 'Fascinated and curious'),
('invigorated', 'positive', 'Energized and refreshed'),
('involved', 'positive', 'Engaged and participating'),
('joyous', 'positive', 'Full of joy'),
('joyful', 'positive', 'Feeling great happiness'),
('jubilant', 'positive', 'Triumphantly joyful'),
('keyed-up', 'positive', 'Excited and energetic'),
('loving', 'positive', 'Feeling or showing love'),
('mellow', 'positive', 'Relaxed and easygoing'),
('merry', 'positive', 'Cheerful and lively'),
('mirthful', 'positive', 'Full of laughter and joy'),
('moved', 'positive', 'Emotionally affected'),
('optimistic', 'positive', 'Hopeful about the future'),
('overjoyed', 'positive', 'Extremely happy'),
('overwhelmed', 'positive', 'Overcome with emotion (positive)'),
('peaceful', 'positive', 'Calm and tranquil'),
('perky', 'positive', 'Lively and cheerful'),
('pleasant', 'positive', 'Agreeable and enjoyable'),
('pleased', 'positive', 'Happy and satisfied'),
('proud', 'positive', 'Feeling satisfaction in achievements'),
('quiet', 'positive', 'Peaceful and calm'),
('radiant', 'positive', 'Glowing with happiness'),
('rapturous', 'positive', 'Filled with great joy'),
('refreshed', 'positive', 'Restored and revitalized'),
('relaxed', 'positive', 'Free from tension'),
('relieved', 'positive', 'Free from anxiety or distress'),
('satisfied', 'positive', 'Content and fulfilled'),
('secure', 'positive', 'Safe and protected'),
('sensitive', 'positive', 'Aware and responsive'),
('serene', 'positive', 'Calm and peaceful'),
('spellbound', 'positive', 'Captivated and fascinated'),
('splendid', 'positive', 'Excellent and impressive'),
('stimulated', 'positive', 'Excited and energized'),
('surprised', 'positive', 'Unexpectedly pleased'),
('tender', 'positive', 'Gentle and caring'),
('thankful', 'positive', 'Grateful and appreciative'),
('thrilled', 'positive', 'Extremely excited'),
('touched', 'positive', 'Emotionally moved'),
('tranquil', 'positive', 'Calm and peaceful'),
('trusting', 'positive', 'Having confidence in others'),
('upbeat', 'positive', 'Optimistic and cheerful'),
('warm', 'positive', 'Friendly and affectionate'),
('wide-awake', 'positive', 'Alert and energetic'),
('wonderful', 'positive', 'Excellent and delightful'),
('zestful', 'positive', 'Full of energy and enthusiasm');

-- Insert negative feelings (when needs are not being met)
INSERT INTO feeling_definitions (feeling, category, definition) VALUES
('afraid', 'negative', 'Feeling fear or anxiety'),
('aggravated', 'negative', 'Annoyed and frustrated'),
('agitated', 'negative', 'Troubled and restless'),
('alarmed', 'negative', 'Worried and frightened'),
('aloof', 'negative', 'Distant and uninvolved'),
('angry', 'negative', 'Feeling strong displeasure'),
('anguished', 'negative', 'Experiencing severe mental distress'),
('annoyed', 'negative', 'Slightly angry and irritated'),
('anxious', 'negative', 'Worried and uneasy'),
('apathetic', 'negative', 'Lacking interest or enthusiasm'),
('apprehensive', 'negative', 'Anxious about the future'),
('ashamed', 'negative', 'Feeling guilt or embarrassment'),
('beat', 'negative', 'Exhausted and worn out'),
('bewildered', 'negative', 'Confused and perplexed'),
('bitter', 'negative', 'Angry and resentful'),
('blah', 'negative', 'Feeling uninspired or apathetic'),
('blue', 'negative', 'Sad and melancholy'),
('bored', 'negative', 'Uninterested and restless'),
('brokenhearted', 'negative', 'Deeply saddened'),
('chagrined', 'negative', 'Distressed and embarrassed'),
('cold', 'negative', 'Unfriendly and distant'),
('confused', 'negative', 'Unable to understand clearly'),
('cross', 'negative', 'Annoyed and bad-tempered'),
('dejected', 'negative', 'Sad and dispirited'),
('depressed', 'negative', 'Feeling very unhappy'),
('despairing', 'negative', 'Without hope'),
('despondent', 'negative', 'In low spirits from loss of hope'),
('detached', 'negative', 'Emotionally distant'),
('disaffected', 'negative', 'Dissatisfied and rebellious'),
('disappointed', 'negative', 'Sad from unmet expectations'),
('discouraged', 'negative', 'Having lost confidence'),
('disenchanted', 'negative', 'Disillusioned'),
('disgruntled', 'negative', 'Angry and dissatisfied'),
('disgusted', 'negative', 'Feeling revulsion'),
('disheartened', 'negative', 'Having lost hope'),
('dismayed', 'negative', 'Distressed and troubled'),
('displeased', 'negative', 'Annoyed and dissatisfied'),
('disquieted', 'negative', 'Worried and uneasy'),
('distressed', 'negative', 'Suffering from anxiety'),
('disturbed', 'negative', 'Worried and upset'),
('downcast', 'negative', 'Feeling dejected'),
('downhearted', 'negative', 'Discouraged and sad'),
('dull', 'negative', 'Lacking interest or excitement'),
('edgy', 'negative', 'Tense and irritable'),
('embarrassed', 'negative', 'Feeling awkward and self-conscious'),
('embittered', 'negative', 'Angry and resentful'),
('exasperated', 'negative', 'Extremely annoyed'),
('exhausted', 'negative', 'Extremely tired'),
('fatigued', 'negative', 'Very tired'),
('fearful', 'negative', 'Afraid and anxious'),
('fidgety', 'negative', 'Restless and impatient'),
('forlorn', 'negative', 'Lonely and abandoned'),
('frightened', 'negative', 'Afraid and scared'),
('frustrated', 'negative', 'Feeling blocked or thwarted'),
('furious', 'negative', 'Extremely angry'),
('gloomy', 'negative', 'Sad and pessimistic'),
('guilty', 'negative', 'Feeling responsible for wrongdoing'),
('harried', 'negative', 'Feeling pressured and stressed'),
('heavy', 'negative', 'Weighed down emotionally'),
('helpless', 'negative', 'Unable to help oneself'),
('hesitant', 'negative', 'Tentative and uncertain'),
('horrible', 'negative', 'Extremely unpleasant'),
('horrified', 'negative', 'Filled with horror'),
('hostile', 'negative', 'Unfriendly and aggressive'),
('hot', 'negative', 'Angry and heated'),
('humdrum', 'negative', 'Lacking excitement, dull'),
('hurt', 'negative', 'Emotionally wounded'),
('impatient', 'negative', 'Restless and eager'),
('indifferent', 'negative', 'Having no interest'),
('irate', 'negative', 'Very angry'),
('irked', 'negative', 'Irritated and annoyed'),
('irritated', 'negative', 'Annoyed and impatient'),
('jealous', 'negative', 'Envious and possessive'),
('jittery', 'negative', 'Nervous and restless'),
('lazy', 'negative', 'Unwilling to work or be active'),
('leery', 'negative', 'Wary and suspicious'),
('lethargic', 'negative', 'Sluggish and lacking energy'),
('listless', 'negative', 'Lacking energy and enthusiasm'),
('lonely', 'negative', 'Sad from being alone'),
('mad', 'negative', 'Angry and furious'),
('mean', 'negative', 'Unkind and spiteful'),
('miserable', 'negative', 'Very unhappy'),
('mopey', 'negative', 'Dejected and listless'),
('morose', 'negative', 'Sullen and ill-tempered'),
('mournful', 'negative', 'Feeling grief or sorrow'),
('nervous', 'negative', 'Anxious and worried'),
('nettled', 'negative', 'Irritated and annoyed'),
('numb', 'negative', 'Unable to feel emotions'),
('panicky', 'negative', 'Feeling sudden overwhelming fear'),
('passive', 'negative', 'Accepting without resistance'),
('perplexed', 'negative', 'Confused and puzzled'),
('pessimistic', 'negative', 'Expecting the worst'),
('puzzled', 'negative', 'Confused and uncertain'),
('rancorous', 'negative', 'Bitter and resentful'),
('reluctant', 'negative', 'Unwilling and hesitant'),
('repelled', 'negative', 'Disgusted and repulsed'),
('resentful', 'negative', 'Bitter and indignant'),
('restless', 'negative', 'Unable to rest or relax'),
('sad', 'negative', 'Feeling sorrow'),
('scared', 'negative', 'Frightened and afraid'),
('shaky', 'negative', 'Unsteady and nervous'),
('shocked', 'negative', 'Surprised and disturbed'),
('skeptical', 'negative', 'Doubtful and questioning'),
('sleepy', 'negative', 'Drowsy and tired'),
('sorrowful', 'negative', 'Full of grief'),
('sorry', 'negative', 'Feeling regret'),
('spiritless', 'negative', 'Lacking energy or enthusiasm'),
('startled', 'negative', 'Suddenly surprised'),
('suspicious', 'negative', 'Distrustful and wary'),
('tepid', 'negative', 'Showing little enthusiasm'),
('terrified', 'negative', 'Extremely frightened'),
('tired', 'negative', 'Needing rest'),
('troubled', 'negative', 'Worried and distressed'),
('uncomfortable', 'negative', 'Feeling unease'),
('unconcerned', 'negative', 'Not worried or interested'),
('uneasy', 'negative', 'Anxious and restless'),
('unglued', 'negative', 'Emotionally falling apart'),
('unhappy', 'negative', 'Not happy or content'),
('unnerved', 'negative', 'Disturbed and unsettled'),
('unsteady', 'negative', 'Not stable or secure'),
('upset', 'negative', 'Troubled and distressed'),
('uptight', 'negative', 'Tense and anxious'),
('vexed', 'negative', 'Annoyed and frustrated'),
('weary', 'negative', 'Tired and exhausted'),
('wistful', 'negative', 'Yearning and melancholy'),
('withdrawn', 'negative', 'Socially detached'),
('woeful', 'negative', 'Full of woe and sorrow'),
('worried', 'negative', 'Anxious about something'),
('wretched', 'negative', 'Very unhappy and unfortunate');

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_feeling_definitions_feeling ON feeling_definitions(feeling);
CREATE INDEX IF NOT EXISTS idx_feeling_definitions_category ON feeling_definitions(category);

-- Sample query to use for autocomplete
-- SELECT feeling FROM feeling_definitions WHERE feeling ILIKE 'exc%' ORDER BY feeling;